use_frameworks!

platform:ios, '10.0'

target 'SwiftWalle_Example' do
  pod 'SwiftWalle', :path => '../'
  pod 'SwiftLint', :configurations => ['Debug']
  target 'SwiftWalle_Tests' do
    inherit! :search_paths
  end
end
